version: '3.8'

services:
  # Data collection pipeline
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
      target: pipeline
    container_name: karlcam-pipeline
    restart: unless-stopped
    
    volumes:
      # Persist collected images and logs
      - data:/app/data
      
    environment:
      - TZ=America/Los_Angeles
      - PYTHONUNBUFFERED=1
      
    # Health check to ensure the collector is working
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/collection_log.json') else 1)"]
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 30s
    
    # Resource limits
    mem_limit: 1g
    cpus: 0.5

  # FastAPI backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: karlcam-backend
    restart: unless-stopped
    
    volumes:
      # Share data with pipeline
      - data:/app/data
      
    environment:
      - TZ=America/Los_Angeles
      - PYTHONUNBUFFERED=1
      
    expose:
      - "8000"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    networks:
      - proxy-network
      - default
    
    # Resource limits
    mem_limit: 2g
    cpus: 1.0

  # Public-facing frontend with simple serve
  public-frontend:
    build:
      context: .
      dockerfile: public-frontend/Dockerfile
    container_name: karlcam-public-frontend
    restart: unless-stopped
    
    ports:
      - "3000:3000"
      
    environment:
      - TZ=America/Los_Angeles
      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    depends_on:
      - backend
    
    networks:
      - proxy-network
      - default
    
    # Resource limits
    mem_limit: 512m
    cpus: 0.5

  # Pipeline management frontend (local network access via DNS)
  pipeline-frontend:
    build:
      context: .
      dockerfile: pipeline-frontend/Dockerfile
    container_name: karlcam-pipeline-frontend
    restart: unless-stopped
    
    ports:
      - "8080:8080"
      
    environment:
      - TZ=America/Los_Angeles
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    depends_on:
      - backend
    
    # Resource limits
    mem_limit: 512m
    cpus: 0.5

volumes:
  data:
    external: true

networks:
  default:
    driver: bridge
  proxy-network:
    external: true