apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karlcam-data
  namespace: karlcam
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi