apiVersion: apps/v1
kind: Deployment
metadata:
  name: karlcam-pipeline-frontend
  namespace: karlcam
  labels:
    app: karlcam-pipeline-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karlcam-pipeline-frontend
  template:
    metadata:
      labels:
        app: karlcam-pipeline-frontend
    spec:
      containers:
      - name: frontend
        image: karlcam/pipeline-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: REACT_APP_API_URL
          value: "http://karlcam-backend"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: karlcam-pipeline-frontend
  namespace: karlcam
spec:
  selector:
    app: karlcam-pipeline-frontend
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP